services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SpecialistaWeb\Newsstylist\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  SpecialistaWeb\Newsstylist\Hooks\NewsStylist12:
    tags:
      - name: event.listener
        identifier: 'newsstylist-flexformhook'
        event: TYPO3\CMS\Core\Configuration\Event\AfterFlexFormDataStructureParsedEvent

  SpecialistaWeb\Newsstylist\Hooks\newsstylist:
    tags:
      - name: event.listener
        identifier: 'newsstylist-flexformhook'
        event: TYPO3\CMS\Core\Configuration\Event\AfterFlexFormDataStructureParsedEvent

